# Generated by Django 5.2.9 on 2025-12-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('tech_stack', models.CharField(help_text='Ej: Django, DRF, PostgreSQL, Docker', max_length=200, verbose_name='Tecnologías')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repositorio')),
                ('live_url', models.URLField(blank=True, verbose_name='Deploy / Demo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill')),
                ('category', models.CharField(help_text='Backend, Frontend, DevOps, Data, etc.', max_length=100, verbose_name='Categoría')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2, verbose_name='Nivel')),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
    ]
